name: Build Docker Image
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        os: [macos-latest]
        arch: [arm64]

    steps:
      # Checkout repository
      - name: Checkout
        uses: actions/checkout@v2

      # Set up QEMU
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      # Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      # Build and push Docker image
      - name: Build and push
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          echo $DOCKER_PASSWORD | docker login --username $DOCKER_USERNAME --password-stdin
          docker buildx create --use
          docker buildx build --platform linux/amd64,linux/arm64 -t liangzexu/chatgpt-proxy:latest .
          docker push liangzexu/chatgpt-proxy:latest
